name: moneyboys
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Utilities
  crypto: ^3.0.3
  intl: ^0.19.0
  uuid: ^4.5.0
  
  # UI Components
  flutter_slidable: ^3.1.0
  fl_chart: ^0.69.0
  table_calendar: ^3.1.3
  
  # Storage & Backend
  shared_preferences: ^2.2.1
  supabase_flutter: ^2.5.10
  
  # AI Integration
  google_generative_ai: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"     

flutter:
  uses-material-design: true
  assets:
    - assets/images/